# Generated by Django 5.1.6 on 2025-02-24 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdocument',
            name='isPublic',
        ),
        migrations.AddField(
            model_name='hospitaldocument',
            name='added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='hospitaldocument',
            name='isPrivate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='patientdocument',
            name='added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='patientdocument',
            name='isPrivate',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='HospitalDoctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.doctor')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.hospital')),
            ],
        ),
    ]
