# Generated by Django 5.1.6 on 2025-03-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_patientdocument_ispublic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitaldocument',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patientdocument',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
