# Generated by Django 5.1.6 on 2025-03-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_hospitaldocument_name_patientdocument_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalledger',
            name='reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hospitalledger',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
