# Generated by Django 5.1.6 on 2025-03-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_hospitalledger_reason_alter_hospitalledger_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdocument',
            name='hash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
