# Generated by Django 5.1.6 on 2025-03-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_patientdocument_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='qr',
            field=models.ImageField(blank=True, null=True, upload_to='qr'),
        ),
    ]
